### ISSUE TITLE
EIRにおいて、exc機能が設定されたコンパートメントのRetention出力がおかしい

### ISSUE THREAD

**Issue by 9rnsr** [9rnsr/FlexID#14]
OIRの計算処理では、出力ステップごとにコンパートメント毎の積算放射能を保持する`Act.Excreta`をゼロクリアしている。
https://github.com/9rnsr/FlexID/blob/f048fd4d9e1dc95c06ad471cdd89b831d260850e/FlexID.Calc/MainRoutine_OIR.cs#L159-L166

これに対してEIRの計算処理では、`Act.Excreta`のゼロクリアがない。
https://github.com/9rnsr/FlexID/blob/f048fd4d9e1dc95c06ad471cdd89b831d260850e/FlexID.Calc/MainRoutine_EIR.cs#L303-L309

この違いにより、Faecesのようなコンパートメントにおいて、OIRでは年齢を経るごとに数値が下がっていくが、EIRでは単調増加する挙動になっており、おそらく正しくない結果が出力されている。

**Comment by 9rnsr** [comment]
@Maron1224 これはバグと考えていいでしょうか？

**Comment by Maron1224** [comment]
@9rnsr はい。バクです。OIRも当初同様の累積されていく現象が起きていたものを修正して頂きました。現状のOIRのexcのコンパートメントでは、Bq/day として排泄率を出力するようにしていると思います。公開版でそのようになっているかは未確認です。

**Comment by 9rnsr** [comment]
@Maron1224 回答ありがとうございます。
