### ISSUE TITLE
RetentionファイルにTotal bodyの結果も出力

### ISSUE THREAD

**Issue by Maron1224** [9rnsr/FlexID#30]
現在、Total body(全身)の残留放射能は、Retentionファイルの全コンパートメントの放射能を時間ごとに積算して、後処理している。そのため、効率化、ミス防止の観点から、RetentionファイルにTotal bodyの結果を出力するように改良して頂けないでしょうか？

**Comment by 9rnsr** [comment]
機能追加は可能です。ただTotal bodyの算出は、合算するコンパートメントを適切に選択する必要があると思うのですが、これは核種毎に異なったりしますでしょうか？　一般論としては、少なくともexcコンパートメントは除外しないとTotal Body算出の目的に合わない気がします。すべての計算方式で共通の合算手順を定義できない場合、適切な数値を出すためにはインプットで合算式を指定する必要が出てきます。

これは余談ですが、上記のような機能追加まで考えると、OIRと互換の「Alimentary Tract」「Lungs」「Skelton」「Liver」といった数値を任意に出せるかもしれません。

**Comment by 9rnsr** [comment]
@Maron1224 #44 にて、全身の放射能を出力する機能を実装してみました。数値の算出方法については、計算モデルを構成する全てのコンパートメントのうち、初期配分にしか使用されないinp、流量を制御するための仮想的なコンパートメントであり残留は常にゼロとなるmix、体外排出されているので除外すべきであるexc、を除いた、言い換えると全てのaccコンパートメントの数値を合算したものを出力するようにしてみました。

**Comment by 9rnsr** [comment]
Whole body以外の数値の出力機能については　#46 に分離しました。
