### ISSUE TITLE
消化管、肺、骨格、肝臓、甲状腺の残留放射能を出力する

### ISSUE THREAD

**Issue by 9rnsr** [9rnsr/FlexID#46]
OIRのデータには、計算モデルの複数コンパートメントの数値を所定の手順で合算した結果として、以下の部位に関する残留放射能の数値が含まれている。これと同等の数値を出力する機能を追加する。

- Alimentary Tract (消化管)
- Lungs (肺)
- Skeleton (骨格)
- Liver (肝臓)
- Thyroid (甲状腺)

これらは、モデル内のいくつかのコンパートメントの数値を合算するだけでなく、全身の血液のうち、どれだけが対象部位の血液となるか示す係数(blood fraction)を、全身の血液コンパートメントの数値の合算結果に掛けたものを加算する必要がある。

そのため、核種および計算モデルごとに、コンパートメントの数値に対する加算と定数値の乗算をインプットで定義し、この計算式に従って残留放射能を算出する機能が必要となる。

**Comment by Maron1224** [comment]
@9rnsr 下図の OIR Data Viewer の Help で示された分配係数を現在は使用していると思います。しかし、今後、この分配係数の変更がある可能性もあること、更にユーザーが変更した計算を要望する場合に対応するため、この血液中の放射能の分配係数をインプットで定義することに同意します。

現状、FlexIDのアウトプットを後処理して計算しているため、この機能追加により利便性が向上します。是非機能追加頂けると助かります。

![image](https://github.com/user-attachments/assets/40a3e144-0743-4ec3-b313-c9ede9877190)

**Comment by 9rnsr** [comment]
最近のS係数周りの改良によって、残留放射能の計算に使用するコンパートメントについては、Publ.133で定義された79個の線源領域との対応関係が明確にインプットで与えられるようになりました。

このことから、例として消化管の残留放射能を計算する場合に、消化管に属する線源領域群を取得し、これらに対応するコンパトメント群の残留放射能を足し合わせる、という手法がとれるかもしれません。

**Comment by Maron1224** [comment]
@9rnsr 現状のインプットの構成から、提示頂いた方法で実現可能と同意致します。
　例えば、骨格として合算されるコンパートメント名称を列記し、実際のインプットに存在するコンパートメントの残留放射能を足し合せ、更に血液中の残留放射能からの加算割合をインプットで指定して骨格の残留放射能に加えた時系列の骨格の残留放射能を出力した方が汎用的で拡張性がありますね。
　やはりインプット形式の可読性向上、合理化の恩恵がこのような所にでますね。
　上記方法ではなくても、決め打ちでコード内埋め込みでもOKです。これらの合算する臓器や血液からの分配係数は、OIRで変わることは無いと思いますので、EIRで課題となればインプットに合算する臓器を指定すれば汎用的に使用できると思います。
　現状のプログラムとインプット形式からベストな方法を適用頂ければ幸いです。
