### ISSUE TITLE
S係数における線源領域Otherはインプットに対応して計算するべき？

### ISSUE THREAD

**Issue by 9rnsr** [9rnsr/FlexID#65]
「その他の軟組織」('other tissues')として取り扱われるべき線源領域のリストは、ICRP Publ.133のSAFデータに含まれる`sregions_2016-08-12.NDX`のID列が`1`になっているものが対応する。しかし、これをFlexIDのインプットにて`Other`に関連付けたコンパートメントの線量計算に用いるかどうかは、インプットにて示される体内動態モデルによって変わってくると考えられる。

例として、`Liver`は「その他の軟組織」に含まれる線源領域だが、Cs-137やSr-90ではこれは動態モデルにてコンパートメントとして明示されているため、線源領域として`Other`を指定されたコンパートメントのS係数は、`Liver`からのSAF値をその計算から除外する必要がある（そうでないとLiverからの各標的領域への寄与が多重に計算されるはず）。

これに対して、例えばBa-133では`Liver`が動態モデルのコンパートメントとして明示されていないため、`Other`のS係数は`Liver`からのSAF値をその計算に含んでいる必要がある。

これらのことから、線源領域`Other`のS係数については、FlexIDのインプットを読み込んだ後、その中でコンパートメントに対応する線源領域して指定されている（＝コンパートメントとして明示されている）ものを「その他の軟組織」から除外した、その残りを使って計算する必要があると考えられる。

**Comment by 9rnsr** [comment]
上に示した考察が正しければ、現在のFlexIDでは核種毎にOtherを含んだS係数データを計算しこれを使用しているが、核種毎のS係数データについてはOtherを含まないものに変更したうえで、OtherのS係数のみインプットを使った線量計算の直前に求める、という手順に変更する必要がある。

**Comment by 9rnsr** [comment]
@Maron1224 見解を頂けると助かります。

**Comment by Maron1224** [comment]
@9rnsr Other tissue のS係数計算方法について検討頂きまして、ありがとうございます。
ICRP Publ.133では、
- **組織系動態モデルで定義されていない線源臓器**の全てを、`その他の組織(Other tissue)`として合計する。(2.5 (p.30))
- sretions_2016-08-12.NDX の ID=1 の線源臓器が`Other tissue`。(B.4 (p.73))

と記載があります。従って、ご指摘の計算方法で正しいです。 
　また、線源臓器の質量は血液を除いた質量を使用（組織系動態モデルに血液コンパートメントが定義されているため）すると、2.4  (p.29) に記載があり、Table A.1(Male), A.2(Female), A.3(Source Region, Male&Female) を比較すると、Table A.3の線源臓器質量は血液を除いた質量となっているため、sretions_2016-08-12.NDX 記載の男女の線源臓器の質量を`Other tissue`のS係数計算(Mother, Mrs)に使用することとなります。
　2017年に一度、SAFファイルの更新が行われ以下が修正されました。
[https://journals.sagepub.com/doi/pdf/10.1177/0146645317741391](url)
その際にファイル名も変更となり、rcp-af_alpha_2017-03-07.SAF のように日付だけ変更されていましたが、現在ICPRのHPではファイル名が元の2016年のものに戻っています。しかし、SAF値は正しく修正された値（両者に相違ないことを確認済み）となっていますので、マニュアルも2017年のファイル名となっているため、次回更新時には修正しましょう。
　sregions_20XX-XX-XX.NDXファイルは2016年と2017年で比較していませんが、2017年のファイルがあれば念のため比較しておきましょう。（今、私の手元にはありません。）

　FlexIDのプログラムとしては、実行時に`Other tissue`のS係数を計算した方が、今後ICRPの定義が変更された場合にも対応できるので汎用性が高いと思います。また、`Other tissue`のS係数はユーザーが意識せずとも内部でS係数計算＋線量計算まで完了し、その結果（Otherの対象となった線源臓器と`Other tissue`のS係数値）がOutputに残るといいですね。

**Comment by 9rnsr** [comment]
@Maron1224 詳細な情報ありがとうございます、線源領域OtherについてのS係数計算処理は改修が必要ということで理解できました。

改良後には、算出したOtherのS係数を新たな出力ファイルに書き出す必要がある点はその通りだと思います。こちらについてはフォーマットを検討いたします。

**Comment by 9rnsr** [comment]
PR #77 にて本機能拡張を実装しました。
