### ISSUE TITLE
S係数計算におけるβ線スペクトルの取り扱いについて

### ISSUE THREAD

**Issue by Maron1224** [9rnsr/FlexID#70]
@9rnsr 以下の点についてプログラムの処理を確認頂けないでしょうか。

1. 単色エネルギーとして取り扱う放射線：G, PG, DG, X, AQ, IE, AE, A, AR, FF
2. **スペクトルデータとして取り扱う放射線**：**B+, B, DB**
3. 中性子(スペクトル＋WRが関数で複雑なため、中性子エネルギー毎のSAFではなく、核種毎のSAFとスペクトル平均WRが示されている。従って、各SAFにスペクトル平均WRを乗じるだけでS係数が計算できる。)：N

**B+, B, DB を放出する核種のβ線スペクトルのS係数計算処理**

- 1つの核種から放出される全てのβ線スペクトル(B+, B, DB)が BETファイル に合成して記載されている。
- そのため、RADファイルに B+, B, DB のうち一つでも記載があれば、当該核種のBETファイルを参照し、（S係数計算にRADファイルの B+, B, DB の情報は不要）単色の場合のS係数式のWR(電子=1.0)を乗じる以外の合算部分（E・Y・SAF）を以下のように台形積分でスペクトルの積分を行う。（ように現行プログラムは作成されているはずです。）

① BETファイルのスペクトルデータはポイントデータであるため、それぞれのデータ点について エネルギー E [MeV] と
　 MeVあたり、ntあたりのβ粒子数 P(E) [/MeV/nt] を乗じる。これが単色での Yield [/nt] となる。
② 次に各データ点の E [MeV] における 電子のSAF値 を 区分的 3 次エルミート内挿多項式 (PCHIP) により内挿補間し、
　①の Yield に乗じる。（ Y・SAF ）
③ 隣り合うデータ点間のエネルギー差 ΔE [MeV] を用いて、2点間の台形積分を行う。
　　{ Y(1)・SAF(1)＋Y(2)・SAF(2) } × ΔE ÷ 2
④ ③を全てのデータ点について実施して総和を取り、最後に放射線加重係数 WR=1.0 を乗じることでβ線スペクトルの 
　S係数 を計算できる。
⑤ 更に、検証対象コードである IDAC Dose2.1 の S係数 の単位 [mGy/MBq] に合わせるため、④で算出した S係数
　[MeV/kg/nt] に 1.60218E-13 を乗じる。（ここはプログラム処理外の話です。）

※ 添付ファイルは Y-90 の 成人男性の Adrenals から Tonsils への S係数 を RADファイル、BETファイル および
　SAFファイル から Excel 計算 したものです。SAFの内挿補間が PCHIP ではなく、線形内挿補間 のため IDAC
　Dose2.1 とは少しズレますが、近い値を示しています。
[Y-90_AdrenalsーTonsils_検証_AM.xlsx](https://github.com/user-attachments/files/16574347/Y-90_Adrenals.Tonsils_._AM.xlsx)

**Comment by 9rnsr** [comment]
@Maron1224 計算方法については上記の通り実装されているようです。

1点、細かいことですが、現状のS係数計算処理は、MeVからJへの換算もS-Coefficientプログラム内で行っており、Excel上ではJ換算を行っていません（MeV→J換算係数の設定用セルは残っているが、数値として1が入っている）。これ自体は換算を行うタイミングが違うだけで結果に影響ないのですが、プログラム内で使っている換算用の係数が`1.602176487E-13`となっており、上に示された`1.60218E-13`より精度が高いようです。またこの数値は、2019年のSI基本単位の再定義によって決定された定義値1.602176634×10<sup>−19</sup>と微妙に異なっており、出典が少し気になります。

https://github.com/9rnsr/FlexID/blob/921045934da4c9e1bc92a0b2c5534fa9a16f1023/S-Coefficient/CalcScoeff.cs#L12-L13

**Comment by Maron1224** [comment]
@9rnsr ありがとうございます。

ICRPで使用されている換算係数は、
　1eV = 1.602E-19 J
とかなり丸められていたと思いますので、ICRP Publ.133刊行年の値を確認して使用しましょうか。
　明日、念のためPubl.133を確認して連絡します。

**Comment by Maron1224** [comment]
> @Maron1224 計算方法については上記の通り実装されているようです。
> 
> 1点、細かいことですが、現状のS係数計算処理は、MeVからJへの換算もS-Coefficientプログラム内で行っており、Excel上ではJ換算を行っていません（MeV→J換算係数の設定用セルは残っているが、数値として1が入っている）。これ自体は換算を行うタイミングが違うだけで結果に影響ないのですが、プログラム内で使っている換算用の係数が`1.602176487E-13`となっており、上に示された`1.60218E-13`より精度が高いようです。またこの数値は、2019年のSI基本単位の再定義によって決定された定義値1.602176634×10−19と微妙に異なっており、出典が少し気になります。
> 
> https://github.com/9rnsr/FlexID/blob/921045934da4c9e1bc92a0b2c5534fa9a16f1023/S-Coefficient/CalcScoeff.cs#L12-L13

@9rnsr ICRP Publ. では、SI単位系を使用。と記載がありますので、ご指摘のとおり正確な
　　1 [MeV] = `1.602176634×10−13` [J]
を使用しましょう。

**Comment by 9rnsr** [comment]
@Maron1224 #73 にて換算係数を更新しました。
