### ISSUE TITLE
収束計算の閾値がOIRとEIRで異なる

### ISSUE THREAD

**Issue by 9rnsr** [9rnsr/FlexID#91]
収束計算では、各コンパートメントで算出した残留放射能の前回値と今回値の差の絶対値が、今回値に対して一定割合以下となるところを収束達成と判定する。この閾値がEIR向け計算では`1E-14`と小さくより精緻に計算され、これに対してOIRは`1E-8`と相対的に粗い計算となっている。

https://github.com/9rnsr/FlexID/blob/18a5e21a16f9fa21e5192806fa31cc37a7eda965/FlexID.Calc/MainRoutine_OIR.cs#L97-L98

https://github.com/9rnsr/FlexID/blob/18a5e21a16f9fa21e5192806fa31cc37a7eda965/FlexID.Calc/MainRoutine_EIR.cs#L83-L84

本件は #87 の修正作業がOIRとEIRの両方に影響するはずの所で、EIRの結果が従来と変わらなかったことで気づいた。これは、EIRの閾値は現在のRetentionファイル出力値(有効数字9桁)を評価期間全域に渡って精度よく求められるが、OIRの閾値はそれには不足する状態であることを意味している。

お試しとしてOIRの閾値を`1E-14`にしてTrialCalcを実行したところ、18核種85個のOIRインプット計算について計算時間は5分→9分と、2倍程度の増加となった。出力値は、有効数字の下4桁程度に差が生じることも確認した。

**Comment by Maron1224** [comment]
@9rnsr ご検討頂きまして、ありがとうございます。

どこまでクライテリアを厳しくすべきかは、今回のOIRを再現するという意味においては、以下の方法はどうでしょうか？

・現在、我々が経験した核種でもっともコンパートメント数の多いCs-137(Ba-137m)の吸入摂取Type F, M, Sの残留放射能をOIRで公開されている全ての残留放射能と比較する。
・このとき、前ステップと現ステップの差の割合で収束判定している判定基準値は、一致度が有意な差とならなくなる段階の値を採用する。

　確かに1E-14とかなり厳しくすれば精度に安心して計算できますが、計算負荷が犠牲になるので、適度な判定基準で、効率的な計算とすることが賢明だと思います。

　この方法を採用する場合は、まずこちらでCs-137(Ba-137m)のインプットを作成します。その後、上記検討をお願いできないでしょうか？

**Comment by 9rnsr** [comment]
@Maron1224 OIRの再現に必要十分かどうか、で閾値の妥当性を考えるということですね。

現状と閾値を厳しくした場合の計算結果を残留放射能で比較すると、すべての出力時間メッシュ、すべてのコンパートメントについて、有効桁の上3桁に差は出ていませんでした。これはCs-137(Ba-137m)でも同様でしたので、このことから現状の閾値はOIRの残留放射能(有効数字2桁)との比較という観点からみると、既に必要十分な精度は確保していると言えます。

こうなると閾値を厳しくすることは計算負荷が増加するだけで利点が少ない、ということになるため、OIRの閾値は現状ママの方が良いと結論付けられそうです。

**Comment by Maron1224** [comment]
@9rnsr 早々にご確認頂きまして、ありがとうございます。
　1点確認ですが、OIRの有効数字2桁とズレない精度と考えた場合、有効数字4桁まで変わらなくなるような判定基準(1E-？)であれば良いと考えます。
　現在の1E-08では、残留放射能の結果が1E-09以上に厳しくした場合と有効数字4桁目まで変化無いでしょうか？

　ご検討頂ければ助かります。

**Comment by 9rnsr** [comment]
@Maron1224 現状の閾値1E-08とより厳しい閾値1E-14の違いとして、実際のところは大半の数値は有効数字4桁程度なら一致してますね。実際に数値の差が3桁目まであるところはごく小数の箇所という感じです。体内で放射性物質の移動が多い、あるいはコンパートメントが多い核種(いずれもコンパートメント間を移動する残留放射能が多い＝収束計算結果の差異が影響しやすい)に対してはもう少し厳しい値の方がいいかもしれませんが、大半の核種では現状で十分だと思います。

**Comment by 9rnsr** [comment]
収束計算の閾値について、現状の1E-08、および1E-14以外に、1E-10、1E-12についても確認してみました。

- 1E-08→1E-10：
    1E-14に対するずれが、大きいところでも下4桁程度から下2桁程度に改善し、ずれが小さいところでは下0～1桁になる。

- 1E-10→1E-12：
    1E-14に対するずれが、大きいところでも下1桁程度まで改善し、ずれが小さいところではほぼ下0桁になる。

OIRの85件のテスト実行時間は手元の環境で以下のようになりました。
|閾値|各テストの実行時間の合計|
|---|---|
|1E-08|55.7 分|
|1E-10|70.9 分|
|1E-12|81.1 分|
|1E-14|93.1 分|

1E-10の時点で上4桁の差異なしは十分達成できているので、OIRの再現性を考えるならこれが一番コストパフォーマンスが良いと思います。

**Comment by Maron1224** [comment]
@9rnsr パラメータサーベイして頂き、ありがとうございました。
　私も `1E-10` で十分であり、もし上4桁が変わらず一致するのであれば、`1E-09` でもいいと思います。
　お陰様で良い設定根拠のエビデンスが残せました。

**Comment by 9rnsr** [comment]
@Maron1224 上記の調査結果は「現在OIRインプットを用意している18核種に対して」という前提があるので、現状で閾値としてギリギリを狙うよりは余裕があったほうがベターかと思います。
では、`1E-10`に変更する方向で進めたいと思います。
