### ISSUE TITLE
情報共有：OIR Data Viewer Help記載内容

### ISSUE THREAD

**Issue by Maron1224** [9rnsr/FlexID#94]
@9rnsr 標記の件、ご存じの内容が多いとは思いますが、念のため情報共有致します。

Helpをコピーした英語のファイルとそれを機械翻訳（＋簡単に修正）したファイルを添付します。

Help ( 英語 ) ：[OIR Data Viewer Help (Eng) .docx](https://github.com/user-attachments/files/16829720/OIR.Data.Viewer.Help.Eng.docx)
Help(日本語)：[OIR Data Viewer Help (Jpn) .docx](https://github.com/user-attachments/files/16829864/OIR.Data.Viewer.Help.Jpn.docx)

### **概要**
**1. `集約された臓器と身体部位`のOIR経時残留放射能データ**
　なお、以下の血液中放射能の各臓器などへの分配は、OIRの定義として集約された臓器と身体部位の残留放射能を表すためのものであり、**S係数を用いた線量計算時は**、**この血液中放射能の分配は実施しない**。血液中の放射能は分配せずに、血液中の放射能として、血液のS係数から線量計算を実施する。
　以下はあくまでもOIRの集約された臓器などと計算結果を比較する場合に必要となる定義である。

-    a) `全身`の放射能は、血液中の放射能全てを含める。
-    b) `消化管`は、胃、小腸、結腸、直腸S状結腸の内容物と壁に加えて、血液コンパートメント中の放射能のうち、**`0.07`** の割合で放射能を含める。
-    c) `肺`は、細気管支、気管支、胸部リンパ節、肺胞間質区画、その他の胸部肺組織に加えて、血液コンパートメント中の放射能のうち、**`0.125`** の割合で放射能を含める。
-    d) `骨格`は、コンパートメントに明示的に指定されている骨表面、骨体積、骨髄に加えて、血液コンパートメント中の放射能のうち、**`0.07`** の割合で放射能を含める。
-    e) `肝臓`は、コンパートメントに明示的に指定されている肝臓コンパートメントに加えて、血液コンパートメント中の放射能のうち、**`0.1`** の割合で放射能を含める。
-    f) `甲状腺`は、コンパートメントに明示的に指定されている甲状腺コンパートメントに加えて、血液コンパートメント中の放射能のうち、**`0.0006`** の割合で放射能を含める。

**2. 排泄関数 `m(t)` について**
- 排泄関数における、急性摂取後の経過時刻 **`t` は**、**`1日単位`である**。
- 例えば、t=0 h ～ t =24 h の m(t) = m(24h) は、摂取時(t=0)から1日(24h)後までの **`尿`** または **`糞`** の **`積算放射能量`** 
 (**`24hサンプル`**)となる。
- サンプル **収集期間** ( **24h** ) **中** のサンプル内の **`放射性崩壊を考慮`** する。

**3. その他**
　以下はOIRの前提条件を記載します。
- OIRでは、作業者の呼吸率 `1.2 m3/h` の各粒径の沈着割合が使用されている。
- 体内動態モデルは、標準成人`男性のパラメータ`が使用されている。
- 1つの`コンパートメント内`では、`放射能は均一に分布`していると仮定。
- 標準作業者のOIRでの体内動態モデルの構造とそのパラメータは、`性別`、`年齢`、`人種`、その他の **`個人固有の特性`には依存しない**。

**Comment by 9rnsr** [comment]
@Maron1224 情報ありがとうございます。#46 の実装などに役立ちそうです。

これはFlexIDの関連情報として有用なので、Wikiなどに移動したほうがいいかもしれませんね。後日、移動を試みます。

**Comment by 9rnsr** [comment]
以下のWikiページへ情報を転載しました。

https://github.com/9rnsr/FlexID/wiki/OIR_Data_Viewer_Help.md
